version: '2'

services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: easy
      MYSQL_DATABASE: easy
      MYSQL_USER: easy
      MYSQL_PASSWORD: easy
  easy:
    depends_on:
    - db
    build: .
    ports:
    - "8808:80"
